[package]
name = "currant"
version = "0.1.0"
edition = "2018"
license-file = "LICENSE"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
shell-words = "1.0.0"
